### ISSUE TITLE
no method named `serialize_pem` found for struct `CertifiedKey` in the current scope

### ISSUE THREAD

**Issue by JoshuaChi** [deventlab/d-engine#3]
```
2025-03-20T11:53:54.165225Z ERROR cargo_tarpaulin: Failed to compile tests!
error[E0599]: no method named `serialize_pem` found for struct `CertifiedKey` in the current scope
   --> src/network/grpc/mod.rs:143:14
    |
143 |         cert.serialize_pem().unwrap(),
    |              ^^^^^^^^^^^^^ method not found in `CertifiedKey`
    |
help: one of the expressions' fields has a method of the same name
    |
143 |         cert.key_pair.serialize_pem().unwrap(),
    |              +++++++++


Error: "Failed to compile tests!\nerror[E0599]: no method named `serialize_pem` found for struct `CertifiedKey` in the current scope\n   --> src/network/grpc/mod.rs:143:14\n    |\n143 |         cert.serialize_pem().unwrap(),\n    |              ^^^^^^^^^^^^^ method not found in `CertifiedKey`\n    |\nhelp: one of the expressions' fields has a method of the same name\n    |\n143 |         cert.key_pair.serialize_pem().unwrap(),\n    |              +++++++++\n\n"
```

Issue comes arises after upgrading rcgen crate from v0.11 to v0.13:

```
# certification
rcgen = { version = "0.13", features = ["pem"] }
```
